# Based on template from
# https://ubuntu.com/blog/ros-2-ci-with-github-actions

name: Build (Ubuntu and ROS2)

on:
  pull_request:
    branches: [ros2]
  push:
    branches: [ros2]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
      fail-fast: false
    steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev

    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.0.15
      with:
        required-ros-distributions: eloquent

    - name: Compile Package
      uses: ros-tooling/action-ros-ci@0.0.16
      with:
        package-name: crazyflie_cpp crazyflie_driver

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()